# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2df02c33e6517dfccc005bf342013d35331ba3d0f8984f0b637f30f1a71b4b96f9d5217e6d4d9ec9180f3ff313c18f3c53eef745ad29d085d21fd6597ae6f5e7

test:
  secret_key_base: 70af0d2e094a732356916f56484da48fa8c0a5842fe064598dc43e9ef00f801e7451f67aa98c3d358476164f2fa13917605433e94546b900b5cc8c45f782b900

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
